pool: MyAgentPool

  - task:UseDotNet@2

inputs:
    
    packageType: 'sdk'
    useGlobalJson: true
    workingDirectory: 'https://github.com/harshalv98/mslearn-tailspin-spacegame-web/'
steps:
- bash: echo hello world